/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTelegramRouteImport } from './routes/_app/telegram'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppCouponsRouteImport } from './routes/_app/coupons'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppAccountingRouteImport } from './routes/_app/accounting'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppProductsNewRouteImport } from './routes/_app/products/new'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products/$productId'
import { Route as AppInventoryScanRouteImport } from './routes/_app/inventory/scan'
import { Route as AppInventoryProductIdRouteImport } from './routes/_app/inventory/$productId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTelegramRoute = AppTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppCouponsRoute = AppCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryScanRoute = AppInventoryScanRouteImport.update({
  id: '/inventory/scan',
  path: '/inventory/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryProductIdRoute = AppInventoryProductIdRouteImport.update({
  id: '/inventory/$productId',
  path: '/inventory/$productId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/accounting': typeof AppAccountingRoute
  '/categories': typeof AppCategoriesRoute
  '/coupons': typeof AppCouponsRoute
  '/orders': typeof AppOrdersRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/telegram': typeof AppTelegramRoute
  '/inventory/$productId': typeof AppInventoryProductIdRoute
  '/inventory/scan': typeof AppInventoryScanRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounting': typeof AppAccountingRoute
  '/categories': typeof AppCategoriesRoute
  '/coupons': typeof AppCouponsRoute
  '/orders': typeof AppOrdersRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/telegram': typeof AppTelegramRoute
  '/': typeof AppIndexRoute
  '/inventory/$productId': typeof AppInventoryProductIdRoute
  '/inventory/scan': typeof AppInventoryScanRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/accounting': typeof AppAccountingRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/coupons': typeof AppCouponsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/telegram': typeof AppTelegramRoute
  '/_app/': typeof AppIndexRoute
  '/_app/inventory/$productId': typeof AppInventoryProductIdRoute
  '/_app/inventory/scan': typeof AppInventoryScanRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounting'
    | '/categories'
    | '/coupons'
    | '/orders'
    | '/sales'
    | '/settings'
    | '/telegram'
    | '/inventory/$productId'
    | '/inventory/scan'
    | '/products/$productId'
    | '/products/new'
    | '/inventory/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounting'
    | '/categories'
    | '/coupons'
    | '/orders'
    | '/sales'
    | '/settings'
    | '/telegram'
    | '/'
    | '/inventory/$productId'
    | '/inventory/scan'
    | '/products/$productId'
    | '/products/new'
    | '/inventory'
    | '/products'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/accounting'
    | '/_app/categories'
    | '/_app/coupons'
    | '/_app/orders'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/telegram'
    | '/_app/'
    | '/_app/inventory/$productId'
    | '/_app/inventory/scan'
    | '/_app/products/$productId'
    | '/_app/products/new'
    | '/_app/inventory/'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/telegram': {
      id: '/_app/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof AppTelegramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coupons': {
      id: '/_app/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AppCouponsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/scan': {
      id: '/_app/inventory/scan'
      path: '/inventory/scan'
      fullPath: '/inventory/scan'
      preLoaderRoute: typeof AppInventoryScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/$productId': {
      id: '/_app/inventory/$productId'
      path: '/inventory/$productId'
      fullPath: '/inventory/$productId'
      preLoaderRoute: typeof AppInventoryProductIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCouponsRoute: typeof AppCouponsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTelegramRoute: typeof AppTelegramRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInventoryProductIdRoute: typeof AppInventoryProductIdRoute
  AppInventoryScanRoute: typeof AppInventoryScanRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCouponsRoute: AppCouponsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTelegramRoute: AppTelegramRoute,
  AppIndexRoute: AppIndexRoute,
  AppInventoryProductIdRoute: AppInventoryProductIdRoute,
  AppInventoryScanRoute: AppInventoryScanRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
