FROM node:20-alpine AS base
RUN npm install -g pnpm

FROM base AS deps
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/admin/package.json apps/admin/
COPY libs/shared-types/package.json libs/shared-types/
COPY libs/shared-utils/package.json libs/shared-utils/
RUN pnpm install --frozen-lockfile

FROM deps AS builder
WORKDIR /app
COPY . .
RUN pnpm nx build admin

FROM nginx:alpine AS runner
COPY --from=builder /app/dist/apps/admin /usr/share/nginx/html
COPY nginx.admin.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
